dist: focal

langauge: cpp

os:
    - linux

compiler:
    - gcc

install:
    - sudo apt update
    - sudo apt install build-essential
    - sudo apt install libgtest-dev
    - sudo apt-get install cmake
    - sudo apt-get install -y valgrind
    - sudo apt-get install -y gcovr
    - sudo apt install lcov
    - sudo apt install cppcheck


script:
    - mkdir build
    - cd build
    - cmake .. -DSTATIC=True
    - make
    - valgrind --leak-check=yes --track-origins=yes --error-exitcode=33 -s ./general_functions_test
    - valgrind --leak-check=yes --error-exitcode=33 -s ./static_test
    - gcovr -r ..
    - cppcheck --enable=all --inconclusive --library=posix ../general_functions_test.cpp
    - cppcheck --enable=all --inconclusive --library=posix ../static_test.cpp
    - time -p ./main
    - cat result.txt

    - rm -rf *

    - cmake ..
    - make
    - valgrind --leak-check=yes --error-exitcode=33 -s ./general_functions_test
    - valgrind --leak-check=yes --error-exitcode=33 -s ./dynamic_test
    - gcovr -r ..
    - cppcheck --enable=all --inconclusive --library=posix ../general_functions_test.cpp
    - cppcheck --enable=all --inconclusive --library=posix ../dynamic_test.cpp
    - time -p ./main
    - cat result.txt


    # 
    # valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=33 -s ./general_functions_test